---
title: "Image Dithering with Bayer Patterns"
author: "J Wood"
date: "1/2/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(imager)
```

##Dither your own image!
The basic code for creating a dithered version of your own image is pulled from the following tutorial. I adapted the fuctions to automatically generalize to any size image you input.

```{r}
#load in your jpg
my_image <- load.image("waindualcats.jpg")
plot(my_image, axes = FALSE)

#making a greyscale version
image_gray <- grayscale( rm.alpha(my_image) )
plot(image_gray, axes = FALSE)
```


Functions which will create 
```{r}
# Calculates a non-normalized Bayer pattern matrix of size 2^n
recursive_bayer_pattern <- function(n) {
  if(n <= 0) {
    return(matrix(0))
  }
  m <- recursive_bayer_pattern(n - 1)
  rbind(
    cbind(4 * m + 0, 4 * m + 2),
    cbind(4 * m + 3, 4 * m + 1))
}

# Returns a Bayer pattern of size 2^n normalized so all values
# are between 0.0 and 1.0.
normalized_bayer_pattern <- function(n) {
  pattern <- recursive_bayer_pattern(n)
  (1 + pattern) / ( 1 + length(pattern) )
}

# rep_mat takes a matrix (mat) and tiles it so that the resulting
# matrix has size nrow_out x ncol_out.
# It's basically a 2d version of rep()
rep_mat <- function(mat, nrow_out, ncol_out) {
  mat[rep(seq_len(nrow(mat)), length.out = nrow_out),
      rep(seq_len(ncol(mat)), length.out = ncol_out)]
}

```

```{r}
#generalized function
dither_my_image <- function(Image, bayer_n=1) {
  #setting up cimg
  bayer_matrix <- rep_mat(normalized_bayer_pattern(bayer_n),
                        nrow(Image), ncol(Image))
  bayer_cimg <- as.cimg(bayer_matrix)
  
  #
  image_bayer <- Image > bayer_cimg
  plot(image_bayer, axes = FALSE)


}

#bayer_n can be 1, 2, or 3 - for Bayer patterns of size 2, 4, and 8 (default = 1)
#Image should be grayscale version of your image
dither_my_image(Image = image_gray, bayer_n = 2)
```

